package io.a2a.spec;

import java.util.List;
import java.util.Map;

import io.a2a.util.Assert;

/**
 * Represents outputs generated by an agent during a task (e.g., generated files or final structured
 * data). Contains parts.
 */
public record Artifact(String name, String description, List<Part> parts, Map<String, Object> metadata,
                       int index, boolean append, boolean lastChunk) {

    public Artifact {
        Assert.checkNotNullParam("parts", parts);
    }

    public static class Builder {
        private String name;
        private String description;
        private List<Part> parts;
        private Map<String, Object> metadata;
        private int index;
        boolean append;
        boolean lastChunk;

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder parts(List<Part> parts) {
            this.parts = parts;
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder index(int index) {
            this.index = index;
            return this;
        }

        public Builder append(boolean append) {
            this.append = append;
            return this;
        }

        public Builder lastChunk(boolean lastChunk) {
            this.lastChunk = lastChunk;
            return this;
        }

        public Artifact build() {
            return new Artifact(name, description, parts, metadata, index, append, lastChunk);
        }
    }
}
